### ISSUE TITLE
Remove powers-of-2 restriction on cohort size

### ISSUE THREAD

**Issue by cygnusv** [nucypher/ferveo#130]
Given that our cohorts will be likely small (i.e. less than 100), we're not going to take advantage of FFT optimizations that introduce the requirement for the cohort size to be a power of 2.

**Comment by piotr-roslaniec** [comment]
- [ ] Benchmark with and without powers-of-2 restrictions

**Comment by arjunhassard** [comment]
Would the optimization of transcript aggregation (KZG etc.) that affords us the possibility (though not necessarily product need) of viable >100 cohorts, also overshadow the relative savings/benefits from FFT optimizations, to the extent that relative benefit of powers-of-2 drops below the cost (inflexible cohort tuning)? 

Regardless, this restriction seems more trouble than it's worth at this stage, so +1 on removing.

**Comment by piotr-roslaniec** [comment]
The "FTT optimization" refers to a set of operations that the validator has to perform in order to produce decryption shares. The tradeoff here is that with FTT we create a constraint (multiples of 2 only) on the number of shares and in exchange get lower latency (validators produce shares faster). So when we talk about FTT optimization we consider the latency in the transcript generation step of the DKG. 

This trade-off is not terribly interesting for us. In the original Ferveo, it was interesting because the latency was tied to a block time (DKG was performed by chain validators), and an ability to squeeze more validators into a shorter time window made sense. For us, having restrictions on the number of shares lifted is more interesting, since we outsourced state management to a data availability layer.

I just want to highlight that this change will _will not_ impact the size of transcripts, it's purely about the amount of computing. However, lifting the restriction on the number of transcripts could help us in selecting DKG configurations that offer us "the best bang for our buck" (gas cost of storage vs number of validators).

**Comment by piotr-roslaniec** [comment]
Added benchmarking results to [this PR](https://github.com/nucypher/ferveo/pull/134)

**Comment by piotr-roslaniec** [comment]
Closed by #134
